src/main/java/vn/viettel/campaign/dto/Path.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.viettel.campaign.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.entities.EvaluationInputObject;

/**
 *
 * @author SON
 */
public class Path {

    private int id;
    private String ObjectName;
    private List<EvaluationInputObject> lstEvaluationInputObject = new ArrayList<>();
    private String filter;
    private EvaluationInputObject inputObject = new EvaluationInputObject();

    private String dataCondition;
    private String dataFunction;

    public static boolean isStringNullOrEmpty1(String input) {
        if (input == null || input.trim().equalsIgnoreCase("") || input.trim().equalsIgnoreCase(" ")) {
            return true;
        }
        return false;
    }

    public String getDataCondition() {
        if (isStringNullOrEmpty1(this.dataCondition)) {
            this.dataCondition = "";
            if (getFilter() != null) {
                String[] result = getFilter().split(";");
                if (result.length == 2 || result.length == 1) {
                    dataCondition = result[0];
                }
            }
        }
        return dataCondition;
    }

    public void setDataCondition(String dataCondition) {
        this.dataCondition = dataCondition;
    }

    public String getDataFunction() {
        if (DataUtil.isStringNullOrEmpty(this.dataFunction)) {
            this.dataFunction = "";
            if (getFilter() != null) {
                String[] result = getFilter().split(";");
                if (result.length == 2) {
                    dataFunction = result[1];
                }
            }

        }
        return dataFunction;
    }

    public void setDataFunction(String dataFunction) {
        this.dataFunction = dataFunction;
    }

    public EvaluationInputObject getInputObject() {
        return inputObject;
    }

    public void setInputObject(EvaluationInputObject inputObject) {
        this.inputObject = inputObject;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getObjectName() {
        return ObjectName;
    }

    public void setObjectName(String ObjectName) {
        this.ObjectName = ObjectName;
    }

    public List<EvaluationInputObject> getLstEvaluationInputObject() {
        return lstEvaluationInputObject;
    }

    public void setLstEvaluationInputObject(List<EvaluationInputObject> lstEvaluationInputObject) {
        this.lstEvaluationInputObject = lstEvaluationInputObject;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }
}

src/main/java/vn/viettel/campaign/entities/Rule.java
/*
 * Copyright 2009-2014 PrimeTek.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package vn.viettel.campaign.entities;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author truongbx
 */
@Entity
@Table(name = "RULE")
@Getter
@Setter
public class Rule extends BaseCategory implements Serializable {

    @Id
    @Column(name = "RULE_ID")
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long ruleId;
    @Column(name = "DESCRIPTION")
    public String description;
    @Column(name = "RULE_NAME")
    public String ruleName;
    @Column(name = "CATEGORY_ID")
    private long categoryId;
    //HaBM2: Update change structure
    @Column(name = "CDR_SERVICE_IDS")
    private String cdrServiceId;
    
    @Transient
    public String segmentName;
    @Transient
    public long segmentId;
    @Transient
    public Integer priority;
    @Transient
    public Segment segment;
    @Transient
    private String name;
    
    public Rule() {
    }

    public Segment getSegment() {
        return segment;
    }

    public void setSegment(Segment segment) {
        if (segment!= null){
            this.segmentName = segment.getSegmentName();
            this.segmentId = segment.getSegmentId();
        }
        this.segment = segment;
    }


    public void setName(String name) {
        this.name = name;
    }
    @Override
    public long getParentId() {
        return getCategoryId();
    }

    @Override
    public String getTreeType() {
        return "rule_online";
    }

    @Override
    public void setParentId(Long id) {
        setCategoryId(id);
    }

    @Override
    public String getName() {
        return this.ruleName;
    }

    @Override
    public Class getParentType() {
        return Category.class;
    }
    public void asMap(Rule rule){
        this.ruleId = rule.getRuleId();
        this.ruleName = rule.getRuleName();
        this.description = rule.getDescription();
        this.categoryId = rule.getCategoryId();
        this.cdrServiceId = rule.getCdrServiceId();
    }
}

src/main/java/vn/viettel/campaign/controller/PreProcessNumberController.java
package vn.viettel.campaign.controller;

import lombok.Getter;
import lombok.Setter;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.common.DateUtils;
import vn.viettel.campaign.constants.Constants;
import vn.viettel.campaign.dto.FilterTable;
import vn.viettel.campaign.dto.PathTable;
import vn.viettel.campaign.entities.*;
import vn.viettel.campaign.service.PreprocessUnitInterface;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.*;

import static vn.viettel.campaign.common.DateUtils.DATETIME_PPU_ZONE;
import vn.viettel.campaign.validate.CheckOnEdit;

/**
 * @author truongbx
 * @date 9/15/2019
 */
@ManagedBean
@ViewScoped
@Getter
@Setter
public class PreProcessNumberController extends BaseCategoryController<PreProcessUnit> implements Serializable {

    @Autowired
    PreprocessUnitInterface preprocessUnitServiceImpl;
    private TreeNode pathRootNode;
    private TreeNode parameterNode;
    private TreeNode selectedPathNode = new DefaultTreeNode();
    private List<InputObject> lstInputObject = new ArrayList<>();
    private List<Category> lstCategoryParameter = new ArrayList<>();
    private Map<Long, InputObject> mapInputObject = new HashMap<>();
    private Map<String, InputObject> mapInputNameObject = new HashMap<>();
    private Map<Long, Function> mapFunction = new HashMap<>();
    private Map<Long, Function> mapFunctionTypeOne = new HashMap<>();
    private List<PathTable> lstPathTable = new ArrayList<>();
    private List<InputObject> lstConditionData = new ArrayList<>();
    private List<Function> lstFunctionData = new ArrayList<>();
    private List<Function> lstFunctionDataTypeOne = new ArrayList<>();
    private List<FilterTable> lstConditionTable = new ArrayList<>();
    private List<FilterTable> lstFunctionTable = new ArrayList<>();
    private List<FilterTable> lstFunctionPathTable = new ArrayList<>();
    private List<Zone> lstZone = new ArrayList<>();
    private List<ZoneMap> lstZoneMap = new ArrayList<>();
    private List<ProcessValue> lstProcessValue = new ArrayList<>();
    private List<ProcessValue> lstProcessValueTemp = new ArrayList<>();
    private List<ProcessParam> lstProcessParams = new ArrayList<>();
    private List<Parameter> lstParameter = new ArrayList<>();
    private Map<Long, Parameter> mapParameter = new HashMap<>();

    private TreeNode parameterSelectedNode = new DefaultTreeNode();
    private boolean disableConditiontable = true;
    private PathTable currentPathTable = new PathTable();
    private PathTable realPathTable;
    private ProcessParam currentProcessParam;
    private TreeNode zoneRootNode;
    private TreeNode selectedZoneNode = new DefaultTreeNode();
    private FunctionParam currentFunctionParam;
    Map<Long, Zone> mapZone = new HashMap<>();

    @Override
    public void init() {
        this.categoryType = Constants.CatagoryType.CATEGORY_PRE_PROCESS_UNIT_NUMBER_TYPE;
        this.currentClass = PreProcessUnit.class;
        lstInputObject = preprocessUnitServiceImpl.getLstInputObject();
        for (InputObject inputObject : lstInputObject) {
            mapInputObject.put(inputObject.getObjectId(), inputObject);
            mapInputNameObject.put(inputObject.getObjectName() + "_" + inputObject.getObjectParentId(), inputObject);
        }
        initPathTree();
        lstFunctionData = preprocessUnitServiceImpl.getLstFunction();
        lstFunctionDataTypeOne = preprocessUnitServiceImpl.getLstFunctionTypeOne();
        lstFunctionData.forEach((e) -> mapFunction.put(e.getFunctionId(), e));
        lstFunctionDataTypeOne.forEach((e) -> mapFunction.put(e.getFunctionId(), e));
        lstZone = preprocessUnitServiceImpl.getLstZone();
        lstZoneMap = preprocessUnitServiceImpl.getLstZoneMap();
        initTreeParameter();
        initZoneTree();
    }

    public void initTreeParameter() {
        lstCategoryParameter = categoryService.getCategoryByType(Constants.CatagoryType.CATEGORY_PARAMETER_TYPE);
        List<Long> longs = new ArrayList<>();
        if (!lstCategoryParameter.isEmpty()) {
            lstCategoryParameter.forEach(item -> longs.add(item.getCategoryId()));
        }
        lstParameter = categoryService.getDataFromCatagoryId(longs, Parameter.class.getSimpleName());
        mapParameter = new HashMap<>();
        lstParameter.forEach((e) -> {
            mapParameter.put(e.getParameterId(), e);
        });
//		parameterNode = getRootNoteCatagory(lstTreeCategory);
        initCategoryTree();
//		buildCatagoryAndChildrentTree(parameterNode.getChildren().get(0),lstTreeCategory,lstParameter);
    }

    public void buildCatagoryAndChildrentTree(TreeNode parentNodeCat, List<Category> listCat, List<Parameter> data) {
        Category parentCat = (Category) parentNodeCat.getData();
        for (Category cat : listCat) {
            if (parentCat.getCategoryId().equals(cat.getParentId())) {
                TreeNode childNodeCat = new DefaultTreeNode("category", cat, parentNodeCat);
                buildCatagoryAndChildrentTree(childNodeCat, listCat, data);
            }
        }
        for (Parameter baseCategory : data) {
            if (baseCategory.getCategoryId().equals(parentCat.getCategoryId())) {
                new DefaultTreeNode("parameter", baseCategory, parentNodeCat);
            }
        }
    }

    @Override
    public void initCurrentValue() {
        currentValue = preprocessUnitServiceImpl.getNextSequense();
        currentValue.setPreProcessType(Constants.PRE_PROCESS_UNIT_NUMBER);
        currentValue.setSpecialFields("isUseParameter:" + currentValue.isUsingParameter());
        //HaBM2: Filter for evaluation
        currentValue.setType(Constants.PPU_TYPE_RULE);
    }

    @Override
    public boolean onValidateObject() {
        if (!validInputField(this.currentValue.getPreProcessName(), "PreProcess unit name", true, true, true)) {
            return false;
        }
        if (preprocessUnitServiceImpl.checkExistPreProcessName(this.currentValue.getPreProcessName(), this.currentValue.getPreProcessId())) {
            duplidateMessage("PreProcess unit name");
            return false;

        }
        if (!validInputField(this.currentValue.getDescription(), "Description", false, true, true)) {
            return false;
        }
        if (!validRequireField(this.currentValue.getDefaultValue(), "Default value")) {
            return false;
        }
        if (!validRequireField(this.currentValue.getInputMode(), "Input mode")) {
            return false;
        }

        if (this.currentValue.getInputMode() == 1) {
            if (!validRequireFieldList(lstPathTable, "Path table")) {
                return false;
            }
            for (PathTable pathTable : lstPathTable) {
                if (pathTable.getObjectId() == -1) {
                    notCompleteMessage("Path table");
                    return false;
                }
            }

        } else if (this.currentValue.getInputMode() == 2) {
            if (!validRequireFieldList(lstFunctionPathTable, "Path table")) {
                return false;
            }
            boolean validFunction = buildDataFunction(lstFunctionPathTable, 1);
            if (!validFunction) {
                notCompleteMessage("Path table");
                return false;
            }
        }
        if (!validRequireFieldList(lstProcessParams, "Normalizer table")) {
            return false;
        }
        List<ProcessParam> lstData = new ArrayList<>();
        lstData.addAll(lstProcessParams);
        Collections.sort(lstData, new ProcessParamsComparator());
        Integer i = -1;
        Map<Long, String> map = new HashMap<>();
        for (ProcessParam processParam : lstData) {
            map.put(processParam.getParamIndex(), "1");
            processParam.calculateConfigInputPPUNumber(this.currentValue.isUsingParameter());
            if (!validRequireField(processParam.getParamIndex(), "Value name in normalizer table")) {
                return false;
            }
            if (!validRequireField(processParam.getValue(), "Parameter value in normalizer table")) {
                return false;
            }
            if (!DataUtil.checkMaxlength(processParam.getValue())) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.maxlength"), "parameter value");
                return false;
            }
            if (!validRequireField(processParam.getPriority(), "Priority in normalizer table")) {
                return false;
            }

            if (i == processParam.getPriority()) {
                errorMsgParams(Constants.REMOTE_GROWL, utilsService.getTex("check.duplicate.table"), "priority", "normalizer");
                return false;
            }
            i = processParam.getPriority();
        }
        map.put(this.currentValue.getDefaultValue(), "");
        for (ProcessValue processValue : lstProcessValue) {
            if (map.get(processValue.getValueId()) == null) {
                errorMsg(Constants.REMOTE_GROWL, utilsService.getTex("check.ppu.processValue"));
                return false;
            }
        }
        return true;
    }

    @Override
    public boolean doDelete() {
        return preprocessUnitServiceImpl.onDeletePreprocessUnit(this.currentValue.getPreProcessId());
    }

    @Override
    public boolean onSaveObject() {
        boolean result = preprocessUnitServiceImpl.onSavePreprocessUnit(this.currentValue, lstProcessParams, lstProcessValue);
        return result;
    }

    @Override
    public void doEdit() {
        lstProcessValue = preprocessUnitServiceImpl.getLstProcessValue(currentValue.getPreProcessId());
        lstProcessParams = preprocessUnitServiceImpl.getLstProcessParam(currentValue.getPreProcessId());

src/main/webapp/preProcessNumber/ChoosePath.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<p:dialog header="Choose path" widgetVar="pathTreePopup" id="pathTreePopup" responsive="true" style="width: 500px"
          modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="Choose path" style="margin-left:10px;"/>
    </f:facet>
    <p:outputLabel value="Object path" style=" margin-left: 9px;"/>
    <div class="spacerHeight"/>
    <h:form id="pathTreeForm" style="width: 500px">
        <p:tree filterMatchMode="contains" id="pathTree" var="node"
                value="#{preProcessNumberController.pathRootNode}"
                filterBy="#{node.objectName}"
                selectionMode="single"
                selection="#{preProcessNumberController.selectedPathNode}"
                style=" border: 0px solid; padding: 0px;width: 500px;height:400px ;overflow-y: auto;">

            <p:treeNode type="root" expandedIcon="ui-icon-folder-open"
                        collapsedIcon="ui-icon-folder-collapsed">
                <h:outputText value="#{node.objectName}"/>
            </p:treeNode>

            <p:treeNode type="object" icon="ui-icon-document">
                <h:outputText value="#{node.objectName}"/>
            </p:treeNode>
        </p:tree>
        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton action="#{preProcessNumberController.validateChoosePath()}"
                                 style="width:auto;float: right;"
                                 icon="fa fa-chevron-down" value="Select"
                                 process="@([id$=pathTreeForm])"
                                 update="@([id$=pathTable]),@([id$=remoteGrowl]),@([id$=inputField])"
                                 oncomplete=" if (!args.validationFailed)   PF('pathTreePopup').hide();">
                </p:commandButton>
            </p:outputPanel>
        </div>
    </h:form>
</p:dialog>
</html>

src/main/webapp/preProcessNumber/DefineValuePopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<p:dialog header="#{preProcessNumberController.editMode eq false ? 'Define value' : 'Define value'}" widgetVar="defineValueDialog" id="defineValueDialog" responsive="true" width="1000px"
          style=" overflow-y: hidden" dynamic="true" modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="#{preProcessNumberController.editMode eq false ? 'Define value' : 'Define value'}" style="margin-left:10px;"/>
    </f:facet>
    <!--<h:form id="createRuleForm">-->
    <h:form id="defineValueForm">

        <!--<h:form id="cdrForm">-->
        <p:outputPanel class="ui-g-12 ui-lg-12" >
            <div class="spacerHeight"/>
            <p:dataTable id="defineValueTable" var="value" value="#{preProcessNumberController.lstProcessValueTemp}"
                         selectionMode="single"
                         reflow="true" widgetVar="defineValueTable"
                         styleClass="table-campaign" style="margin-top: 10px;height: 450px ; overflow-y: auto"
                         paginator="true" rows="10"
                         rowKey="#{value.processValueId}"
                         editable="true"
                         rowsPerPageTemplate="5,10,15,20" lazy="false">
                <f:facet name="header">
                    <p:outputLabel value="Value table"
                                   style="float: left; font-weight: bold; font-size: 16px"/><span
                        style="color: red ;float: left">*</span>
                    <p:commandButton icon="fa fa-plus" value="Row" style="float: right; margin-left: 5px;width: auto;"
                                     action="#{preProcessNumberController.onAddDefineValue()}"
                                     update="@([id$=defineValueTable])"
                                     onstart="PF('defineValueTable').paginator.setPage(0);"/>
                </f:facet>
                <p:column headerText="Value Id" colspan="2">
                    <h:outputText value="#{value.valueId}" min="0"/>
                </p:column>
                <p:column headerText="Value Name" colspan="2">
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Value Name"
                                 value="#{value.valueName}">
                        <p:ajax  event="change" delay="500" process="@([id$=defineValueForm])"  update="@([id$=defineValueForm])"></p:ajax>
                    </p:inputText>
                </p:column>
                <p:column headerText="Value Color" colspan="2" style="background-color: #{value.valueColor}">
                    <p:outputPanel class="ui-g-12 ui-lg-9">
                        <p:inputText onchange="this.value = this.value.trim()" placeholder="Value Color"
                                     value="#{value.valueColor}"
                                     id="valueColor">
                            <p:ajax  event="change" delay="500"   update="@this,@([id$=colorPicker])" global="false"></p:ajax>
                        </p:inputText>
                    </p:outputPanel>
                    <p:outputPanel class="ui-g-12 ui-lg-3">
                        <p:colorPicker value="#{value.valueColor}" id="colorPicker">
                            <p:ajax  event="change"  update="@([id$=valueColor])" global="false"></p:ajax>
                        </p:colorPicker>
                    </p:outputPanel>
                </p:column>


                <p:column headerText="Description" colspan="2">
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Description"
                                 value="#{value.description}" >
                        <p:ajax  event="change" delay="500"  process="@([id$=defineValueForm])"  update="@([id$=defineValueForm])"></p:ajax>
                    </p:inputText>
                </p:column>

                <p:column headerText="Action" colspan="1">
                    <p:commandLink action="#{preProcessNumberController.onRemoveDefineValue(value)}"
                                   process=" @this "
                                   update="@([id$=defineValueTable]),@([id$=remoteGrowl])">
                        <h:outputText value="" class="ui-icon ui-icon-trash" style=" width: 100%;"/>
                        <p:confirm header="Confirmation"
                                   message="Are you sure to delete this value?"
                                   icon="fa fa-warning"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>
        </p:outputPanel>

        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton action="#{preProcessNumberController.onSaveProcessValue()}"
                                 style="width:auto;float: right;"
                                 icon="fa fa-floppy-o" value="Apply"
                                 process=" @this ,@([id$=defineValueForm])"
                                 update="@([id$=tableForm]),@([id$=remoteGrowl])"
                                 oncomplete=" if (!args.validationFailed)   PF('defineValueDialog').hide();">
                    <p:ajax></p:ajax>
                </p:commandButton>
            </p:outputPanel>
        </div>
    </h:form>
</p:dialog>
</html>

src/main/webapp/preProcessNumber/categoryCreateOrEditPopup.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<p:dialog header="#{preProcessNumberController.updateCategory eq false ? 'Create category' :'Update category'}"
          widgetVar="carDialog" id="carDialog" responsive="true" modal="true">
    <f:facet name="header">
        <i class="fa fa-list" style="font-size: 14px;"></i>
        <h:outputText value="#{preProcessNumberController.updateCategory eq false ? 'Create category' :'Update category'}" style="margin-left:10px;"/>
    </f:facet>
    <h:form id="catagoryfrm" style="width: 635px !important">
        <p:outputPanel class="ui-g ui-fluid">
            <p:outputPanel class="ui-g-12 ui-lg-6">
                <p:outputLabel value="Category id"/><span style="color: red">*</span>
                <div class="spacerHeight"/>
                <p:inputText onchange="this.value = this.value.trim()" placeholder="Category id"
                             id="categoryId"
                             readonly="true"
                             value="#{preProcessNumberController.category.categoryId}"

                             requiredMessage="Category id is required"
                             validatorMessage="Category id not contains '%' character">
                    <f:validateRegex pattern="^[^%]*$"/>

                </p:inputText>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6">
                <p:outputLabel value="Category name"/><span style="color: red">*</span>
                <div class="spacerHeight"/>
                <p:inputText onchange="this.value = this.value.trim()" placeholder="Category name"
                             id="categoryName"
                             value="#{preProcessNumberController.category.name}"
                             title="#{preProcessNumberController.category.name}"
                             requiredMessage="Category name is required"  autocomplete="off">

                    <p:ajax update="@this" process="@this" global="false"/>
                </p:inputText>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6">
                <p:outputLabel value="Category type"/><span style="color: red">*</span>
                <div class="spacerHeight"/>
                <p:inputText onchange="this.value = this.value.trim()" placeholder="Category type"
                             readonly="true"
                             id="categoryType"
                             required="true"
                             value="PPU Number"
                             requiredMessage="Category type is require"/>
            </p:outputPanel>

            <p:outputPanel class="ui-g-12 ui-lg-6" rendered="#{preProcessNumberController.category.parentId != null}">
                <p:outputLabel value="Parent category"/>
                <div class="spacerHeight"/>
                <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                 value="#{preProcessNumberController.category.parentId}"
                                 id="parentCategory"
                                 rendered="#{preProcessNumberController.updateCategory eq false}">
                    <f:selectItems value="#{preProcessNumberController.categories}"
                                   var="item"
                                   itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                   itemValue="#{item.categoryId}"/>
                </p:selectOneMenu>
                <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                 value="#{preProcessNumberController.category.parentId}"
                                 id="parentCategoryEdit"
                                 rendered="#{preProcessNumberController.updateCategory eq true}">
    
                    <f:selectItems value="#{preProcessNumberController.categories}"
                                   var="item"
                                   itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                   itemValue="#{item.categoryId}"/>
                </p:selectOneMenu>
            </p:outputPanel>
            <p:outputPanel class="ui-g-12 ui-lg-6"></p:outputPanel>
        </p:outputPanel>

        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton icon="fa fa-remove" value="Cancel"
                                 style="width:auto;float: right;"
                                 process="@this"
                                 oncomplete="PF('carDialog').hide();"/>
                    <p:commandButton action="#{preProcessNumberController.validateCategory()}"
                                     style="width:auto;float: right;" 
                                      icon="fa fa-floppy-o" value="Save"
                                     process="@([id$=catagoryfrm])"
                                     update="@([id$=remoteGrowl])"
                                     oncomplete="if (!args.validationFailed) PF('dlgConfirm').show();">
                    </p:commandButton>
                </p:outputPanel>
            </div>
        </h:form>
    </p:dialog>

<p:dialog header="Confirmation" widgetVar="dlgConfirm" modal="true" height="100" id="categoryConfirm">
    <h:outputText value="#{preProcessNumberController.updateCategory eq false ? 'Are you sure to create this Category?' : 'Are you sure to edit this Category?'}" />

    <div class="card card-w-title">
        <p:outputPanel class="ui-g-12 ui-lg-12">
            <p:commandButton value="No"
                             style="width:auto;float: right;"
                             process="@this"
                             oncomplete="PF('dlgConfirm').hide();"/>

            <p:commandButton action="#{preProcessNumberController.doSaveOrUpdateCategory()}"
                             style="width:auto;float: right;"
                             value="Yes"
                             process="@([id$=catagoryfrm]),@this"
                             update="@([id$=fromTree]),@([id$=remoteGrowl])"
                             oncomplete="PF('dlgConfirm').hide();PF('carDialog').hide();">
            </p:commandButton>
        </p:outputPanel>
    </div>
</p:dialog>
</html>