src/main/java/vn/viettel/campaign/entities/AssessmentRule.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.viettel.campaign.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author ABC
 */
@Entity
@Table(name = "assessment_rule")
public class AssessmentRule extends BaseCategory implements Serializable, TreeItemBase {

    private static final Long serialVersionUID = 1L;
    @Id
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "RULE_ID")
    private Long ruleId;
    @Basic(optional = false)
    @Column(name = "RULE_NAME")
    private String ruleName;
    @Column(name = "DESCRIPTION")
    private String description;
    @Basic(optional = false)
    @Column(name = "CATEGORY_ID")
    private Long categoryId;

    public AssessmentRule() {
    }

    public AssessmentRule(Long ruleId, String ruleName, String description, Long categoryId) {
        this.ruleId = ruleId;
        this.ruleName = ruleName;
        this.description = description;
        this.categoryId = categoryId;
    }

    public Long getRuleId() {
        return ruleId;
    }

    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public String getFilter() {
        return getRuleName();
    }

    public void mapData(AssessmentRule assessmentRule) {
        this.ruleId = assessmentRule.getRuleId();
        this.ruleName = assessmentRule.getRuleName();
        this.description = assessmentRule.getDescription();
        this.categoryId = assessmentRule.getCategoryId();
    }

    @Override
    public long getParentId() {
        return  this.getCategoryId();
    }

    @Override
    public void setParentId(Long id) {
         setCategoryId(id);
    }

    @Override
    public String getTreeType() {
        return "object";
    }

    @Override
    public String getName() {
        return this.ruleName;
    }

    @Override
    public Class getParentType() {
        return Category.class;
    }
}

src/main/java/vn/viettel/campaign/controller/AssessmentRuleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.viettel.campaign.controller;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import lombok.Getter;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;
import org.primefaces.PrimeFaces;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.servlet.support.RequestContext;
import vn.viettel.campaign.common.DataUtil;
import vn.viettel.campaign.constants.Constants;
import vn.viettel.campaign.constants.Constants.CatagoryType;
import static vn.viettel.campaign.controller.BaseController.errorMsg;
import static vn.viettel.campaign.controller.BaseController.errorMsgParams;
import static vn.viettel.campaign.controller.BaseController.successMsg;
import vn.viettel.campaign.dto.Expression;
import vn.viettel.campaign.dto.NodeDefineDTO;
import vn.viettel.campaign.dto.NodeInfo;
import vn.viettel.campaign.entities.AssessmentRule;
import vn.viettel.campaign.entities.AssessmentRuleKpiProcessorMap;
import vn.viettel.campaign.entities.AssessmentRulePreProcessUnitMap;
import vn.viettel.campaign.entities.BaseCategory;
import vn.viettel.campaign.entities.CampaignEvaluationInfo;
import vn.viettel.campaign.entities.Category;
import vn.viettel.campaign.entities.CriteriaValue;
import vn.viettel.campaign.entities.FuzzyRule;
import vn.viettel.campaign.entities.KpiProcessor;
import vn.viettel.campaign.entities.PpuEvaluation;
import vn.viettel.campaign.entities.ResultClass;
import vn.viettel.campaign.entities.KpiProcessorCriteriaValueMap;
import vn.viettel.campaign.entities.PreProcessValueMap;
import vn.viettel.campaign.entities.ProcessValue;
import vn.viettel.campaign.entities.RuleEvaluationInfo;
import vn.viettel.campaign.entities.SegmentEvaluationInfo;
import vn.viettel.campaign.service.AssessmentRuleService;
import vn.viettel.campaign.service.CategoryService;
import vn.viettel.campaign.service.TreeUtilsService;
import vn.viettel.campaign.service.UtilsService;

/**
 *
 * @author ABC
 */
@ManagedBean(name = "assessmentRuleController")
@ViewScoped
@Getter
@Setter
public class AssessmentRuleController extends BaseController implements Serializable {

    private TreeNode rootNode;
    private TreeNode kpiNode;
    private TreeNode ppuNode;
    private TreeNode rootNodeFuzzy;
    private TreeNode selectedNode;
    private TreeNode selectedNodeAssessmentRule;
    private TreeNode currentNote;
    private TreeNode currenRootNode;

    private AssessmentRule assessmentRule;
    private AssessmentRule backupAssessmentRule;
    private Category category;
    private Category categoryBackUp;
    private AssessmentRulePreProcessUnitMap assessmentRulePreProcessUnitMap;
    private AssessmentRuleKpiProcessorMap assessmentRuleKpiProcessorMap;
    private KpiProcessorCriteriaValueMap kpiProcessorCriteriaValueMap;
    private PpuEvaluation ppuEvaluation;
    private PpuEvaluation ppuEvaluationMap;
    private KpiProcessor kpiProcessor;
    private KpiProcessor kpiProcessorMap;
    private ResultClass resultClass;
    private FuzzyRule fuzzyRule;
    private FuzzyRule fuzzyRuleEdit;
    private Expression expression;
    private NodeDefineDTO nodeDefineDTO;
    private NodeInfo nodeInfo;

    private List<AssessmentRule> listAssessmentRule;
    private List<AssessmentRule> listAssessmentRuleToDelete = new ArrayList<>();
    private List<AssessmentRulePreProcessUnitMap> listAssessmentRulePreProcessUnitMap;
    private List<AssessmentRuleKpiProcessorMap> listAssessmentRuleKpiProcessorMap;
    private List<CampaignEvaluationInfo> listCampaignEvaluationInfo;
    private List<SegmentEvaluationInfo> listSegmentEvaluationInfo;
    private List<Category> categories;
    private List<Category> categoriess = new ArrayList<>();
    private List<Category> categoryKpi = new ArrayList<>();
    private List<Category> categoryPPU = new ArrayList<>();
    private List<PpuEvaluation> listPpuEvaluation;
    private List<PpuEvaluation> listPpuEvaluationToDelete;
    private List<PpuEvaluation> listPpuEvaluationBuildTree = new ArrayList<>();
    private List<KpiProcessor> listKpiProcessor;
    private List<KpiProcessor> listKpiProcessorToDelete;
    private List<KpiProcessor> listKpiProcessorBuildTree = new ArrayList<>();
    private List<ResultClass> listResultClass;
    private List<ResultClass> listResultClassMap;
    private List<ResultClass> listResultClassToDelete = new ArrayList<>();
    private List<FuzzyRule> listFuzzyRule;
    private List<FuzzyRule> listFuzzyRuleToDelete = new ArrayList<>();
    private List<FuzzyRule> listFuzzyRuleToCheck = new ArrayList<>();
    private List<CriteriaValue> listCriteriaValue = new ArrayList<>();
    private List<KpiProcessorCriteriaValueMap> listkpiProcessorCriteriaValueMap = new ArrayList<>();
    private List<PreProcessValueMap> listPreProcessValueMap = new ArrayList<>();
    private List<ProcessValue> listProcessValue = new ArrayList<>();
    private List<RuleEvaluationInfo> listRuleEvaluationInfo = new ArrayList<>();

    public Map<Long, TreeNode> treeNodeExpanded = new HashMap<>();

    private List<NodeInfo> listNodeInfo = new ArrayList<>();
    private List<NodeInfo> listNodeInfoToDelete = new ArrayList<>();

    private boolean disPlays;
    private boolean action;
    private boolean assessmentRuleEditMoe;
    private boolean renderedCbb;
    private boolean fuzzyEditMode;
    private boolean expressionEditMode;
    private boolean expressionParentEditMode;
    private boolean groupEditMode;
    private boolean groupParentEditMode;
    private boolean showFuzzyMode;
    private boolean categoryEditMode;
    private boolean editMode;
    private boolean focusCombobox = false;
    private boolean focusValuEx = false;
    private boolean focusComboboxResult = false;

    private int checkOption;
    private int checkOptionClick;
    private int dem;
    private int count;

    private String objectTypeToEdit = "";
    private String ppuNameMap;
    private String kpiNameMap;

    @Autowired
    private TreeUtilsService treeUtilsService;
    @Autowired
    private CategoryService categoryService;
    @Autowired
    private AssessmentRuleService assessmentRuleService;
    @Autowired
    private UtilsService utilsService;

    @ManagedProperty(value = "#{ppuEvaluationController}")
    PPUEvaluationController ppuEvaluationController;

    @ManagedProperty(value = "#{kpiProcessorController}")
    KpiProcessorController kpiProcessorController;

    @PostConstruct
    public void init() {
        this.listAssessmentRule = new ArrayList<>();
        this.categories = new ArrayList<>();
        this.listAssessmentRulePreProcessUnitMap = new ArrayList<>();
        this.listAssessmentRuleKpiProcessorMap = new ArrayList<>();
        this.listPpuEvaluation = new ArrayList<>();
        this.listKpiProcessor = new ArrayList<>();
        this.listResultClass = new ArrayList<>();
        this.listFuzzyRule = new ArrayList<>();
        this.listPpuEvaluationToDelete = new ArrayList<>();
        this.listKpiProcessorToDelete = new ArrayList<>();
        this.listCampaignEvaluationInfo = new ArrayList<>();
        this.listSegmentEvaluationInfo = new ArrayList<>();
        initTreeNode();
    }

    public void initTreeNode() {
        this.categories = categoryService.getCategoryByType(CatagoryType.CATEGORY_ASSESSMENT_RULE_TYPE);
        List<Long> longs = new ArrayList<>();
        if (!categories.isEmpty()) {
            categories.forEach(item -> longs.add(item.getCategoryId()));
        }
        this.listAssessmentRule = categoryService.getDataFromCatagoryId(longs, Constants.ASSESSMENT_RULE);
        rootNode = treeUtilsService.createTreeCategoryAndComponentCampaignEvaluation(categories, listAssessmentRule);
        rootNode.getChildren().get(0).setExpanded(true);
        addExpandedNode(rootNode.getChildren().get(0));

    }

    // ASESSMENT_RULE
    //edit
    public void prepareUpdateAssessmentRule() {
        //initTreeNode();
        this.objectTypeToEdit = "object";
        this.disPlays = true;
        this.editMode = true;
        this.action = true;

        this.listKpiProcessorToDelete = new ArrayList<>();
        this.listPpuEvaluationToDelete = new ArrayList<>();
        this.listResultClassToDelete = new ArrayList<>();
        this.listFuzzyRuleToDelete = new ArrayList<>();
        this.assessmentRuleEditMoe = true;
        AssessmentRule asssessment = (AssessmentRule) selectedNode.getData();
        this.assessmentRule = assessmentRuleService.findAssessmentRuleById(asssessment.getRuleId());
        this.currenRootNode = this.selectedNode;
        this.backupAssessmentRule = new AssessmentRule();
        cloneAssessmentRule(backupAssessmentRule, assessmentRule);
        this.listPpuEvaluation = assessmentRuleService.getListPpuEvaluationByRuleId(assessmentRule.getRuleId());
        this.listKpiProcessor = assessmentRuleService.getListKpiProcessorByRuleId(assessmentRule.getRuleId());
        this.listResultClass = assessmentRuleService.getListResultClassByAssessmentRuleId(assessmentRule.getRuleId());
        this.listAssessmentRulePreProcessUnitMap = assessmentRuleService.getAllAssessmentRulePreProcessUnitMapById(assessmentRule.getRuleId());
        this.listAssessmentRuleKpiProcessorMap = assessmentRuleService.getAlllistAssessmentRuleKpiProcessorMapById(assessmentRule.getRuleId());

src/main/webapp/AssessmentRule/AssessmentRuleAndCategoryTree.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:form id="fromTree">

        <div class="title-wrap">
            <div class="title-name">Assessment Rule List</div>
        </div>
        <!--habm2-end-->



        <p:tree filterMatchMode="contains"  id="treeCategory" var="node"
                value="#{assessmentRuleController.rootNode}"
                filterBy="#{node.filter}"
                selectionMode="single" 
                selection="#{assessmentRuleController.selectedNode}"
                style="height: calc(100vh - 101px) !important; border: 0px solid; padding: 0px;width: 100%;overflow: auto;">
             <p:ajax event="select" 
                    listener="#{assessmentRuleController.prepareEditWhenClick()}"
                    update="@([id$=mainContent]),@([id$=carDialog]),@([id$=content]),@([id$=remoteGrowl])"/>

            <p:treeNode type="category" expandedIcon="ui-icon-folder-open" 
                        collapsedIcon="ui-icon-folder-collapsed">
                <h:outputText value="#{node.name}" title="#{node.name}"/>
            </p:treeNode>

            <p:treeNode type="object" icon="ui-icon-document">
                <h:outputText value="#{node.ruleName}" title="#{node.ruleName}"/>
            </p:treeNode>


            <p:treeNode type="folderkpi" icon="ui-icon-folder-open">
                <h:outputText value="#{node.processorName}" title="#{node.processorName}"/>
            </p:treeNode>
            
            <p:treeNode type="kpi" icon="ui-icon-document">
                <h:outputText value="#{node.processorName}" title="#{node.processorName}"/>
            </p:treeNode>
            
            <p:treeNode type="folderppu" icon="ui-icon-folder-open">
                <h:outputText value="#{node.preProcessName}" title="#{node.preProcessName}"/>
            </p:treeNode>

            <p:treeNode type="ppu" icon="ui-icon-document">
                <h:outputText value="#{node.preProcessName}" title="#{node.preProcessName}"/>
            </p:treeNode>


            <p:ajax event="expand" listener="#{assessmentRuleController.onNodeExpand}"></p:ajax>
            <p:ajax event="collapse" listener="#{assessmentRuleController.onNodeCollapse}"></p:ajax>
        </p:tree>

        <p:contextMenu for="treeCategory" nodeType="category" style="width: auto;">
            <p:menuitem icon="fa fa-floppy-o" 
                        value="Create category" 
                        action="#{assessmentRuleController.preapreCreateCategory()}"
                        update="@([id$=carDialog])"
                        oncomplete="PF('carDialog').show()"/>
            <p:menuitem icon="fa fa-refresh" 
                        value="Edit category"
                        action="#{assessmentRuleController.preapreUpdateCategory()}"
                        update="@([id$=carDialog])"
                        oncomplete="PF('carDialog').show()"/>
            <p:menuitem icon="fa fa-trash" 
                        value="Delete category" 
                        action="#{assessmentRuleController.deleteCategory()}"
                        update="@([id$=content]),@([id$=remoteGrowl])">
                <p:confirm header="Confirmation" message="You definitely want to delete ?" icon="ui-icon-alert"/>
            </p:menuitem>
            <p:menuitem icon="fa fa-plus" 
                        value="Create Assessment Rule" 
                        action="#{assessmentRuleController.prepareCreateAssessmentRule()}"
                        update="@([id$=mainContent])"/>
        </p:contextMenu>

        <p:contextMenu for="treeCategory" nodeType="object" style="width: auto;">
            <p:menuitem icon="fa fa-refresh" 
                        value="Edit Assessment Rule" 
                        action="#{assessmentRuleController.prepareUpdateAssessmentRule()}"
                        update="@([id$=mainContent]), @([id$=treeCategory])"/>
            <p:menuitem icon="fa fa-trash" 
                        value="Delete Assessment Rule" 
                        action="#{assessmentRuleController.deleteAssessmentRule()}"
                        update="@([id$=treeCategory]),@([id$=remoteGrowl]),@([id$=mainContent])">
                <p:confirm header="Confirmation" message="Do you want to delete this Assessment Rule ?" icon="ui-icon-alert"/>
            </p:menuitem>
        </p:contextMenu>

    </h:form>




</html>

src/main/webapp/AssessmentRule/PopupCategoryCreateOrUpdate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <p:dialog header="#{assessmentRuleController.categoryEditMode eq false ? 'Create category' :'Update category'}"
              widgetVar="carDialog" id="carDialog" responsive="true" modal="true">
        <f:facet name="header">
            <i class="fa fa-list" style="font-size: 14px;"></i>
            <h:outputText value="#{assessmentRuleController.categoryEditMode eq false ? 'Create category' :'Update category'}" style="margin-left:10px;"/>
        </f:facet>
        <h:form id="catagoryfrm" style="width: 635px !important">
            <p:outputPanel class="ui-g ui-fluid">
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category id"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category id"
                                 id="categoryId"
                                 readonly="true"
                                 value="#{assessmentRuleController.categoryBackUp.categoryId}"
                                 requiredMessage="Category id is required"
                                 validatorMessage="Category id not contains '%' character">
                        <f:validateRegex pattern="^[^%]*$"/>

                    </p:inputText>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category name"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category name"
                                 id="categoryName"
                                 value="#{assessmentRuleController.categoryBackUp.name}"
                                 title="#{assessmentRuleController.categoryBackUp.name}"
                                 requiredMessage="Category name is required"
                                 validatorMessage="Category name not contains '%' character">
                        <f:validateRegex pattern="^[^%]*$"/>
                        <p:ajax update="@this" process="@this"/>
                    </p:inputText>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6">
                    <p:outputLabel value="Category type"/><span style="color: red">*</span>
                    <div class="spacerHeight"/>
                    <p:inputText onchange="this.value = this.value.trim()" placeholder="Category type"
                                 readonly="true"
                                 id="categoryType"
                                 required="true"
                                 value="#{assessmentRuleController.categoryBackUp.categoryType == 32 ? 'Assessment Rule' : ''}"
                                 requiredMessage="Category type is require"/>
                </p:outputPanel>

                <p:outputPanel class="ui-g-12 ui-lg-6" rendered="#{assessmentRuleController.categoryBackUp.parentId != null}">
                    <p:outputLabel value="Parent category"/>
                    <div class="spacerHeight"/>
                    <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                      value="#{assessmentRuleController.categoryBackUp.parentId}"
                                      id="parentCategory"
                                      rendered="#{assessmentRuleController.categoryEditMode eq false}">
                        <f:selectItems value="#{assessmentRuleController.categories}"
                                       var="item"
                                       itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                       itemValue="#{item.categoryId}"/>
                    </p:selectOneMenu>
                    <p:selectOneMenu  syncTooltip="true"  filterMatchMode="contains"  filter="true" style="margin-bottom:10px;"
                                      value="#{assessmentRuleController.categoryBackUp.parentId}"
                                      id="parentCategoryEdit"
                                      rendered="#{assessmentRuleController.categoryEditMode eq true}">

                        <f:selectItems value="#{assessmentRuleController.categories}"
                                       var="item"
                                       itemLabel="#{item.name}" itemDescription="#{item.name}" 
                                       itemValue="#{item.categoryId}"/>
                    </p:selectOneMenu>
                </p:outputPanel>
                <p:outputPanel class="ui-g-12 ui-lg-6"></p:outputPanel>
            </p:outputPanel>

            <div class="card card-w-title">
                <p:outputPanel class="ui-g-12 ui-lg-12">
                    <p:commandButton icon="fa fa-remove" value="Cancel"
                                     style="width:auto;float: right;"
                                     process="@this"
                                     oncomplete="PF('carDialog').hide();"/>
                    <p:commandButton 
                        style="width:auto;float: right;" 
                        icon="fa fa-floppy-o" value="Save"
                        process="@([id$=catagoryfrm])"
                        action="#{assessmentRuleController.validateCategory()}"
                        update="@([id$=remoteGrowl])"
                        oncomplete="if (!args.validationFailed) PF('dlgConfirm').show();">
                    </p:commandButton>
                </p:outputPanel>
            </div>
        </h:form>
    </p:dialog>

    <p:dialog header="Confirmation" widgetVar="dlgConfirm" modal="true" height="100" id="categoryConfirm">
        <h:outputText value="#{assessmentRuleController.categoryEditMode eq false ? 'Are you sure to create this Category?' : 'Are you sure to edit this Category?'}" />
        <p:outputPanel class="ui-g-12 ui-lg-12" >
            <p:outputLabel class="ui-g-12 ui-lg-12" style="border-bottom: 1px solid #a8acb1; width: 100%"  />
        </p:outputPanel>
        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton value="No"
                                 style="width:auto;float: right;"
                                 process="@this"
                                 oncomplete="PF('dlgConfirm').hide();"/>

                <p:commandButton action="#{assessmentRuleController.saveCategory()}"
                                 style="width:auto;float: right;"
                                 value="Yes"
                                 process="@([id$=catagoryfrm]),@this"
                                 update="@([id$=treeCategory]),@([id$=remoteGrowl]),@([id$=mainContent])"
                                 oncomplete="PF('carDialog').hide(),PF('dlgConfirm').hide();" >
                </p:commandButton>
            </p:outputPanel>
        </div>
    </p:dialog>
</html>

src/main/webapp/AssessmentRule/PopupTreeKPI.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <p:dialog header="Choose KPI"
              widgetVar="kpiTreeId" id="kpiTreeId" responsive="true" modal="true"
              style="height: 450px !important;">
        <f:facet name="header">
            <i class="fa fa-list" style="font-size: 14px;"></i>
            <h:outputText value="Choose KPI" style="margin-left:10px"/>
        </f:facet>

        <h:form  style="height: 450px !important;width: 500px !important;overflow-x: hidden">

            <p:tree     filterMatchMode="contains" 
                        var="node"
                        filterBy="#{node.filter}"
                        value="#{assessmentRuleController.kpiNode}"
                        selectionMode="single"
                        selection="#{assessmentRuleController.selectedNode}"
                        style=" border: 0px solid; padding: 0px; height:auto;">
                <p:ajax event="select" />
                <p:treeNode type="category" expandedIcon="ui-icon-folder-open"
                            collapsedIcon="ui-icon-folder-collapsed" >
                    <h:outputText value="#{node.name}" title="#{node.name}"/>
                </p:treeNode>

                <p:treeNode type="object" icon="ui-icon-document">
                    <h:outputText value="#{node.processorName}" title="#{node.processorName}"/>
                </p:treeNode>
            </p:tree>

        </h:form>
        <div class="card card-w-title" >
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton icon="fa fa-undo" value="Cancel"
                                 style="width:auto;float: right;"
                                 process="@this" 
                                 oncomplete="PF('kpiTreeId').hide()">
                </p:commandButton>
                <p:commandButton  style="width:auto;float: right;" 
                                  process="@this" 
                                  icon="fa fa-check"  value="Apply"
                                  action="#{assessmentRuleController.validateKPI()}"
                                  update="@([id$=remoteGrowl])"
                                  oncomplete="if (!args.validationFailed) PF('dlgConfirmkpiTreeId').show()">
                </p:commandButton>
            </p:outputPanel>
        </div>
    </p:dialog>
    <p:dialog header="Confirmation"
              widgetVar="dlgConfirmkpiTreeId"
              id="dlgConfirmkpiTreeId"
              modal="true"
              height="100">
        <h:outputText value="Are you sure to choose this?" />
        <p:outputPanel class="ui-g-12 ui-lg-12" >
            <p:outputLabel class="ui-g-12 ui-lg-12" style="border-bottom: 1px solid #a8acb1; width: 100%"  />
        </p:outputPanel>
        <div class="card card-w-title">
            <p:outputPanel class="ui-g-12 ui-lg-12">
                <p:commandButton value="No"
                                 style="width:auto;float: right;"
                                 process="@this"
                                 oncomplete="PF('dlgConfirmkpiTreeId').hide();"/>

                <p:commandButton style="width:auto;float: right;"
                                 value="Yes"
                                 action="#{assessmentRuleController.chooseKPI()}"
                                 update="@([id$=kpiTable])"
                                 oncomplete="PF('kpiTreeId').hide(),PF('dlgConfirmkpiTreeId').hide()">
                </p:commandButton>
            </p:outputPanel>
        </div>
    </p:dialog>

</html>